### ISSUE TITLE
Is there a way to know the exact type of the unexpected event?

### ISSUE THREAD

**Issue by freak82** [boost-experimental/sml#67]
Hi,

Does the library provides a way to get the real event type from unexpected_event<>?
I just need a way to know the event which provokes the unexpected transition (something like the no_transition functionality from boost meta state machine library). So far I was able to
deal with it without using the unexpected_event functionality with the following code. 

    template <typename E>                                                           
    static auto event_name(E) // A bit hacky way to convert type to string             
    {                                                                               
        return __PRETTY_FUNCTION__; // GCC/Clang specific macro                     
    }                                                                               
                                                                                
    template <typename Event>                                                       
    void agg_writer::process_event(Event ev) noexcept                               
    {                                                                                  
        if (!sm_.process_event(ev))                                                 
        {                                                                           
            sm_.visit_current_states(                                               
                [ev](const auto& state)                                             
                {                                                                   
                    ::printf("No transition from state %s on %s\n",            
                             state.c_str(), event_name(ev));                        
                });                                                             
        }                                                                           
    } 

And in case of error it gives me something like this message:
"Invalid transition from state some_state on auto event_name(E) [with E = some_event]"

It was was good enough for me, because it allowed me easily to spot the bug in my code and fix it.
However, with the latest library version the process event seems to no longer return boolean, and the above approach is not applicable. I tried similar thing using the unexpected_event<> functionality:

    struct on_unexpected                                                                
    {                                                                                   
        template <typename Event>                                                       
        void operator()(Event ev)                                                       
        {                                                                               
            std::cout << "generic unexpected_event" << event_name(ev) << '\n';          
        }                                                                               
    }; 

    return make_transition_table(                                                   
            *("idle"_s) + "event1"_e ...
            ...
          ,   "unexpected events handling"_s  + unexpected_event<> / on_unexpected{} = X
       );   

However, it doesn't work so well and gives only the internal library stuff:
eneric unexpected_even tauto event_name(E) [with E = boost::sml::v1_1_0::detail::_]

Is there a way to get the exact event type without specifying all possible unexpected_events in the transition table? If there is not such a way, will there be a problem to return the boolean type returned by the process_event function in case of no transition? 

Thanks.

**Comment by krzysztof-jusiak** [comment]
Thanks @freak82 for reporting this issue.
It should be fixed by https://github.com/boost-experimental/sml/commit/eb2d87564bfff1f88e22d554c9d1cfdca6ad96bb

If it comes to process event returning value. Well, I had to remove it as it wasn't clear what it was actually returning. In principle, it should be whether an event was handled or not, however, it got much more complex to explain what does could mean in a case of deferred events and different combinations.

Also, if you just need logging in such case, why not to use a logging policy for that?
```cpp
#include <iostream>
#include <typeinfo>
#include <cassert>
#include <boost/sml.hpp>

namespace sml = boost::sml;

// events
struct e1 { };
struct e2 { };
struct e3 { };

struct my_logger {
  template <class SM, class TEvent>
  void log_process_event(const TEvent&) {
    printf("[%s][process_event] %s\n", typeid(SM).name(), typeid(TEvent).name());
  }

  template <class SM, class TGuard, class TEvent>
  void log_guard(const TGuard&, const TEvent&, bool result) {
    printf("[%s][guard] %s %s %s\n", typeid(SM).name(), typeid(TGuard).name(), typeid(TEvent).name(),
           (result ? "[OK]" : "[Reject]"));
  }

  template <class SM, class TAction, class TEvent>
  void log_action(const TAction&, const TEvent&) {
    printf("[%s][action] %s %s\n", typeid(SM).name(), typeid(TAction).name(), typeid(TEvent).name());
  }

  template <class SM, class TSrcState, class TDstState>
  void log_state_change(const TSrcState& src, const TDstState& dst) {
    printf("[%s][transition] %s -> %s\n", typeid(SM).name(), src.c_str(), dst.c_str());
  }
};

struct example {
  auto operator()() const {
    using namespace sml;
    // clang-format off
    return make_transition_table(
      *"idle"_s + event<e1> = "s1"_s
    );
    // clang-format on
  }
};

int main() {
  using namespace sml;

  my_logger l;
  sm<example, logger<my_logger>> sm{l};
  sm.process_event(e1{});
  sm.process_event(e2{});
  sm.process_event(e3{});
}
```
prints...
```
[7example][process_event] 2e1
[7example][transition] idle -> s1
[7example][process_event] N5boost3sml6v1_1_06detail16unexpected_eventINS2_1_E2e2EE
[7example][process_event] N5boost3sml6v1_1_06detail16unexpected_eventINS2_1_E2e3EE
```

Anyway, example with generic unexpected event below.

```cpp
#include <iostream>
#include <typeinfo>
#include <cassert>
#include <boost/sml.hpp>

namespace sml = boost::sml;

// events
struct e1 { };
struct e2 { };
struct e3 { };

struct example {
  auto operator()() const {
    using namespace sml;
    // clang-format off
    return make_transition_table(
      *"idle"_s + event<e1> = "s1"_s
     , "s1"_s + unexpected_event<e2> / [](const auto& event) { std::cout << "unexpected event: " << typeid(event).name() << std::endl; }
     , "s1"_s + unexpected_event<_>  / [](const auto& event) { std::cout << "generic unexpected event: " << typeid(event).name() << std::endl; } = X
    );
    // clang-format on
  }
};

int main() {
  using namespace sml;

  sm<example> sm;

  sm.process_event(e1{});
  assert(sm.is("s1"_s));

  sm.process_event(e2{});
  assert(sm.is("s1"_s)); // unexpected_event e2

  sm.process_event(e3{});
  assert(sm.is(X)); // generic unexpected_event e3
}
```
prints...
```
unexpected event: 2e2
generic unexpected event: 2e3
```

**Comment by mpatrick02702** [comment]
Kris, 

I'm sorry if this is the wrong place to ask this. Please let me know what forum I should use. 

I'd like to second the need for the MSM-like "no_transition" handler. I'm trying to port a 100-transition MSM to SML, and the lack of a "no_transition" handler is significantly hindering my unit testing.   I have a big job ahead to convince my colleagues to switch from MSM to SML, and the lack of a "no_transition" header is a big disadvantage. 

The problem with sml::unexpected_event<_> is that it only matches the case for an event that _appears nowhere else in the transition table_.  It can't  handle the  needed "no_transition" use case  for an  unexpected event that _does_ appear in the transition table for some other state.    

For example, try putting "process_event(e2{})" as the first event.    That event isn't handled in the "idle" state.  But SML is silent in this case, taking no action, because e2 is handled in another state (the unexpected_event(e2) adds it to the event list).    Even if I add the "generic" unexpected event handler for the "idle" state with
            , "idle"_s + unexpected_event<_>  / [](const auto& event) { std::cout << "generic unexpected event: " << typeid(event).name()\
 << std::endl; } = X
The unexpected e2 event in "idle" state is still not detected by SML, because "unexpected_event<_>" only matches non-appearing events. 

Furthermore,  your use of  "unexpected_event<e2>"  is not helpful, because getting that action requires adding an explicit "unexpected_event"  for _every_  "unexpected" event in _every_ state, which defeats the whole purpose of the "no_transition" generic handler. 

Ideally, we need a "no_transition<_>"  internal event that applies to a single region only and means an offered event had no transition in that region's current state.  

As an alternate, please have "process_event()" return a boolean again, so we can use freak82's excellent hack for detecting no transition.  As for the return value,  process_event()  should return nonzero if any region of any SM or sub-SM was in a state with an explicit rule for that event, regardless of what that explicit rule was. This includes a rule to  transition back to the same state, an action with no transition, or the "defer" action.  It includes the explicit ignoring of an event with an action of "[]{}" and no next state. 

I noticed from experiments that transition guards are checked in forward sequence order, so I presume SML checks events in forward sequence order as well.  A less desirable alternate is a generic "sml::event<_>"  syntax that can be placed as the last-appearing transition rule for a state that matches any event that hasn't been matched yet.  It's action would be the "no_transition" handler for that state. 

michael.patrick@harmonicinc.com
